### ISSUE TITLE
Shieldoo: All hosts disconnected (Blocklisting cert, websocket: bad handshake)

### ISSUE THREAD

**Issue by insta-ruv** [cloudfieldcz/shieldoo-mesh-docs#25]
### Question
Shieldoo has been running well for many months but I updated Docker on my server, and after rebooting the mesh network was down. I upgraded to the latest container version at the time of writing and check the lighthouse container's logs there are lots of messages like the following
```
NEBULA#: {"fingerprint":"59400b3bff3df306a946919ad906aac2b8641f7dbd815108ea495a5b47ff6076","level":"info","msg":"Blocklisting cert","time":"2024-12-03T20:45:16Z"}
```

Also, this message:
```
time="2024-12-03T20:45:16Z" level=error msg="repeating start of nebula: Failed to get a tun/tap device (map[]): operation not permitted"
```

On the hosts connecting to the lighthouse 
```
Dec 03 22:48:31 power shieldoo-mesh-srv[1122458]: NEBULA+: {"durationNs":6499881907,"handshake":{"stage":1,"style":"ix_psk0"},"initiatorIndex":1633739234,"level":"info","localIndex":1633739234,"msg":"Handshake timed out","remoteIndex":0,"time":"2024-12-03T22:48:31+02:0>
Dec 03 22:48:32 power shieldoo-mesh-srv[1122458]: time="2024-12-03T22:48:32+02:00" level=info msg="ws connect: websocket: bad handshake"
```

I'm not sure what's going on as everything stopped working after the host reboot.
The CA is still valid and wasn't touched. The server's SSL certificate is valid.
I can reach the frontend admin page so the Traefik reverse proxy works (also latest version as of writing).

Any advice on what might have happened or went wrong and how to fix it?

**Comment by valda-z** [comment]
After upgrading to Ubuntu 22.04, your Docker container's access to `/dev/net/tun` may be hindered due to changes in Docker's security policies or kernel module handling. The TUN device (`/dev/net/tun`) is essential for tunneling protocols like VPNs, and restricted access can disrupt services relying on it.

**Potential Causes:**

1. **Docker Security Enhancements:** Recent Docker updates might have tightened security, limiting container access to certain devices. This can prevent containers from creating or accessing `/dev/net/tun`.

2. **Kernel Module Loading:** The TUN module (`tun.ko`) may not be loaded automatically after the upgrade, making `/dev/net/tun` unavailable.

**Solutions:**

1. **Explicitly Allow Access to `/dev/net/tun`:**

   - **Modify Docker Compose Configuration:**
     Add the following lines to your service definition in `docker-compose.yml`:

     ```yaml
     devices:
       - /dev/net/tun:/dev/net/tun
     ```

     This binds the host's TUN device into the container, ensuring it's accessible. 

   - **Add Necessary Capabilities:**
     Ensure the container has the required capabilities to manage network interfaces:

     ```yaml
     cap_add:
       - NET_ADMIN
       - MKNOD
     ```

     The `NET_ADMIN` capability allows network administration tasks, while `MKNOD` permits the creation of device files. 

2. **Load the TUN Module on the Host:**

   - **Check if the TUN Module is Loaded:**
     Run:

     ```bash
     lsmod | grep tun
     ```

     If there's no output, the TUN module isn't loaded.

   - **Load the TUN Module:**
     Execute:

     ```bash
     sudo modprobe tun
     ```

     This command loads the TUN module into the kernel.

   - **Ensure the Module Loads at Boot:**
     Add `tun` to `/etc/modules` to load it automatically on startup:

     ```bash
     echo 'tun' | sudo tee -a /etc/modules
     ```

     This ensures the TUN module is available after reboots. 

3. **Adjust Container Privileges (If Necessary):**

   - **Run the Container in Privileged Mode:**
     As a last resort, run the container with elevated privileges:

     ```yaml
     privileged: true
     ```

     This grants the container full access to the host's devices but should be used cautiously due to security implications. 

**Verification:**

- **Inside the Container:**
  After applying the changes, access the container's shell and check for the presence of `/dev/net/tun`:

  ```bash
  ls -l /dev/net/tun
  ```

  The output should indicate that `/dev/net/tun` exists and has the correct permissions (e.g., `crw-rw-rw-`).

- **Service Functionality:**
  Restart the affected services within the container and monitor their logs to confirm proper operation.

**Note:** Always back up your configurations before making changes and test in a controlled environment to prevent disruptions.

**Comment by valda-z** [comment]
let me know if it helps, I can update docs there

**Comment by insta-ruv** [comment]
Thank you for the insights!
We're indeed running it with Docker. Everything was deployed according to the docker compose repo on Github.

We'll definitely be trying these solutions and we'll be updating select apt packages to narrow it down conclusively.
Hopefully it helps others out there that might get the same surprise.

Figuring out how to deploy multiple lighthouses will be the next step in order to reduce the impact of such surprises.

**Comment by valda-z** [comment]
Cool, anyway solution is ready for 4 lighthouses. It is only question of deployment configuration.
